#!/bin/sh
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^((main|master)|(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\/[a-zA-Z0-9-]+)|((release)/[0-9.]+[a-z0-9.-]*)$"

message="\nThere is something wrong with your branch name.

Branch names in this repository must adhere to a commitlint pattern.

Your push will be rejected. Please rename your branch to a valid name and try again.\n"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
